name: frontend
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  pin_code_fields: ^7.3.0
  flutter_otp_text_field: ^1.1.2
  image_picker: ^0.8.5+3
  font_awesome_flutter: ^10.1.0
  google_maps_flutter: ^2.1.1
  geolocator: ^8.0.0
  http: ^1.2.2  
  shared_preferences: ^2.0.11 
  email_otp: ^3.0.2
  provider:
  # location: ^4.3.0
  intl: ^0.17.0
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/Alogo.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/images/img1.jpg
    - assets/images/img2.jpg
    - assets/images/img3.png
    - assets/images/

  fonts:
    - family: SourceSansPro
      fonts:
        - asset: assets/fonts/SourceSansPro-Regular.ttf
        - asset: assets/fonts/SourceSansPro-Bold.ttf
        - asset:  assets/fonts/SourceSansPro-ExtraLight.ttf
          weight: 700
